name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1"
        # go is already installed by actions/setup-go with the correct version from go.mod
        install-go: false

